### ISSUE TITLE
how to interrupt selected task?

### ISSUE THREAD

**Issue by hotpeperoncino** [nodys/clussh#1]
Hi.
I'm looking for software like clussh. but i cannot find out which has task cancel functionality.
does clussh cancel a task in execution ?

**Comment by nopnop** [comment]
Hi @hotpeperoncino,
No, not really: `clussh` make sure to cancel remote running task if you kill the main process (the clussh process). This is usually not the case with tools using ssh to run script remotely. 
But, if I'm interpreting well your need, clussh does not allows you cancel one task in particular. Still, I'm open to the feature idea: is it what you're looking for?

**Comment by hotpeperoncino** [comment]
hi.yes.i`ve implemented outside og clush itself  by invoking clush as child
process. child process can be stopped forcely. thank you for your reply.

2018年3月17日(土) 19:56 Jean Ponchon <notifications@github.com>:
